using System.Text.Json;
using Microsoft.Playwright;

namespace Zakira.Replay.Core;

/// <summary>
/// Network-event observer that recognises SharePoint Stream / OneDrive's transcripts
/// metadata endpoint and follows the <c>temporaryDownloadUrl</c> for each listed transcript
/// to harvest captions using cookie-auth from the active Playwright context.
/// </summary>
/// <remarks>
/// <para>Background: SharePoint Stream's web player does NOT use the HTML5 <c>textTracks</c>
/// API to expose caption tracks (the entries on <c>&lt;video&gt;.textTracks</c> are stubs
/// whose <c>cues</c> arrays never populate), and it does NOT fetch caption files as
/// <c>.vtt</c>/<c>.srt</c> URLs the existing <see cref="PlaywrightVideoCaptureClient"/>
/// caption interceptor can match on. Instead, when the player initialises it requests a
/// SharePoint REST endpoint that returns JSON listing all transcripts attached to the
/// drive item:</para>
/// <code>
/// GET /personal/{upn}/_api/v2.X/drives/{drive-id}/items/{item-id}?select=media/transcripts,audioTracks&amp;$expand=media/transcripts,media/audioTracks
/// </code>
/// <para>The response shape (observed against an MS-internal Stream recording):</para>
/// <code>
/// {
///   "media": {
///     "transcripts": [
///       {
///         "id": "7e8a9a20-...",
///         "displayName": "MyMeeting.json",
///         "languageTag": "en-GB",
///         "transcriptType": "subtitle",
///         "isAutoGenerated": false,
///         "isDefault": true,
///         "source": "microsoft teams",
///         "temporaryDownloadUrl": "https://.../media/transcripts/{id}/content"
///       }
///     ]
///   }
/// }
/// </code>
/// <para>This class watches for that response, parses out the transcript list, follows each
/// <c>temporaryDownloadUrl</c> via <see cref="IBrowserContext.APIRequest"/> (which carries
/// the Edge profile cookies), and converts the body into standard WebVTT. The body itself
/// is typically the Microsoft Teams transcript JSON shape (entries with <c>start</c>,
/// <c>end</c>, <c>text</c>, <c>speakerDisplayName</c>); we also gracefully handle raw VTT
/// or unrecognised shapes (writing the raw body and emitting a warning).</para>
/// </remarks>
internal sealed class SharePointStreamInterceptor
{
    // Pattern for any URL referencing a drive item. We use it both to recognise the
    // transcript-metadata response and to harvest (drive-id, item-id) tuples from EVERY
    // SharePoint API call observed during capture \u2014 so we can proactively query the
    // metadata endpoint ourselves later, even when the player happens not to.
    private static readonly System.Text.RegularExpressions.Regex DriveItemPathRegex = new(
        @"(?<api>/_api(?:_cached)?/v\d+(?:\.\d+)?)/drives/(?<drive>[^/]+)/items/(?<item>[^/?]+)",
        System.Text.RegularExpressions.RegexOptions.Compiled | System.Text.RegularExpressions.RegexOptions.IgnoreCase);

    private readonly BrowserCaptureRequest request;
    private readonly List<ReplayWarning> warnings;
    private readonly List<Task<TranscriptEntry[]?>> pendingMetadata = [];
    private readonly Dictionary<string, DriveItemRef> observedItems = new(StringComparer.OrdinalIgnoreCase);
    private readonly object lockObj = new();

    public SharePointStreamInterceptor(BrowserCaptureRequest request, List<ReplayWarning> warnings)
    {
        this.request = request;
        this.warnings = warnings;
    }

    public void OnResponse(object? sender, IResponse response)
    {
        try
        {
            if (response.Status >= 400) return;

            // Always opportunistically harvest (drive-id, item-id) from any matching URL \u2014
            // even non-transcripts endpoints like /labelPolicies and /analytics/allTime carry
            // these identifiers, and we want them in case the player never queries the
            // transcripts endpoint itself.
            TryRecordDriveItemRef(response.Url);

            if (!IsTranscriptMetadataUrl(response.Url)) return;

            var task = LoadAndParseMetadataAsync(response);
            lock (lockObj)
            {
                pendingMetadata.Add(task);
            }
        }
        catch
        {
            // never throw from the event handler
        }
    }

    private void TryRecordDriveItemRef(string url)
    {
        if (string.IsNullOrWhiteSpace(url)) return;
        try
        {
            var match = DriveItemPathRegex.Match(new Uri(url).AbsolutePath);
            if (!match.Success) return;

            var apiSegment = match.Groups["api"].Value;
            var driveId = match.Groups["drive"].Value;
            var itemId = match.Groups["item"].Value;
            if (string.IsNullOrWhiteSpace(driveId) || string.IsNullOrWhiteSpace(itemId)) return;

            // Use the host + api segment + drive + item as the canonical key so we don't
            // collide across orgs.
            var origin = new Uri(url).GetLeftPart(UriPartial.Authority);
            // Prefer the writable v2.X endpoint when both v2.X and _api_cached are seen for
            // the same item. The transcripts query has to hit the non-cached endpoint.
            var canonicalApi = apiSegment.Replace("_api_cached", "_api", StringComparison.OrdinalIgnoreCase);
            var key = $"{origin}{canonicalApi}/drives/{driveId}/items/{itemId}".ToLowerInvariant();

            lock (lockObj)
            {
                if (!observedItems.ContainsKey(key))
                {
                    observedItems[key] = new DriveItemRef(origin, canonicalApi, driveId, itemId);
                }
            }
        }
        catch
        {
            // ignore parse failures
        }
    }

    /// <summary>
    /// Returns true when the URL looks like a SharePoint Stream transcript-metadata query.
    /// The shape we look for is <c>/_api/v{N}.{M}/drives/{drive-id}/items/{item-id}?</c>
    /// with a query string referencing <c>media/transcripts</c>. Conservative: misses are
    /// fine (we just won't extract); false positives would attempt parsing a non-Stream
    /// response, which the parser handles gracefully.
    /// </summary>
    internal static bool IsTranscriptMetadataUrl(string url)
    {
        if (string.IsNullOrWhiteSpace(url)) return false;
        try
        {
            var u = new Uri(url);
            var path = u.AbsolutePath;
            var query = u.Query;

            // The metadata URL itself never contains "/media/transcripts/" as a path segment
            // (that's the per-transcript content endpoint). We're looking for an item query
            // that *requests* media/transcripts in its $select or $expand parameters.
            var pathLooksRight = System.Text.RegularExpressions.Regex.IsMatch(
                path,
                @"/_api/v\d+(\.\d+)?/drives/[^/]+/items/[^/?]+/?$",
                System.Text.RegularExpressions.RegexOptions.IgnoreCase);
            if (!pathLooksRight) return false;

            // Query must reference media/transcripts in either select or expand. Match both
            // the URL-encoded form (media%2Ftranscripts) and the decoded form.
            var q = query.ToLowerInvariant();
            return q.Contains("media%2ftranscripts", StringComparison.Ordinal)
                || q.Contains("media/transcripts", StringComparison.Ordinal);
        }
        catch
        {
            return false;
        }
    }

    private async Task<TranscriptEntry[]?> LoadAndParseMetadataAsync(IResponse response)
    {
        byte[] body;
        try
        {
            body = await response.BodyAsync().ConfigureAwait(false);
        }
        catch (PlaywrightException)
        {
            return null;
        }

        return ParseMetadataBytes(body, response.Url);
    }

    /// <summary>
    /// Parse a transcripts-metadata response body. Shared between the passive interception
    /// path (player fetched it on its own) and the proactive fetch path (we requested it
    /// ourselves after observing the drive-item id elsewhere). Returns an empty array when
    /// the JSON is valid but lists no transcripts; returns null when the body isn't parseable.
    /// </summary>
    private TranscriptEntry[]? ParseMetadataBytes(byte[] body, string sourceUrl)
    {
        if (body.Length == 0) return null;

        try
        {
            using var doc = JsonDocument.Parse(body);
            if (!doc.RootElement.TryGetProperty("media", out var media)) return [];
            if (!media.TryGetProperty("transcripts", out var transcripts)) return [];
            if (transcripts.ValueKind != JsonValueKind.Array) return [];

            var list = new List<TranscriptEntry>();
            foreach (var t in transcripts.EnumerateArray())
            {
                var id = TryGetString(t, "id");
                var url = TryGetString(t, "temporaryDownloadUrl");
                if (string.IsNullOrWhiteSpace(url)) continue;

                list.Add(new TranscriptEntry(
                    Id: id ?? Guid.NewGuid().ToString("N"),
                    DisplayName: TryGetString(t, "displayName"),
                    LanguageTag: TryGetString(t, "languageTag"),
                    TranscriptType: TryGetString(t, "transcriptType"),
                    Source: TryGetString(t, "source"),
                    IsAutoGenerated: TryGetBool(t, "isAutoGenerated"),
                    IsDefault: TryGetBool(t, "isDefault"),
                    TemporaryDownloadUrl: url!));
            }
            return list.ToArray();
        }
        catch (JsonException ex)
        {
            warnings.Add(new ReplayWarning(
                ReplayWarningCodes.CaptureStreamMetadataParseFailed,
                $"SharePoint Stream transcript metadata response from {sourceUrl} was not valid JSON: {ex.Message}",
                Source: "stream",
                Severity: ReplayWarningSeverities.Warning));
            return null;
        }
    }

    public async Task<IReadOnlyList<BrowserCapturedCaption>> DownloadAllAsync(
        IBrowserContext context,
        CancellationToken cancellationToken)
    {
        Task<TranscriptEntry[]?>[] snapshot;
        DriveItemRef[] itemRefs;
        lock (lockObj)
        {
            snapshot = pendingMetadata.ToArray();
            itemRefs = observedItems.Values.ToArray();
        }

        // First: drain anything the player asked for itself (the passive interception path).
        var unique = new List<TranscriptEntry>();
        if (snapshot.Length > 0)
        {
            try
            {
                await Task.WhenAll(snapshot).ConfigureAwait(false);
            }
            catch
            {
                // ignore; per-task failures handled below
            }

            unique.AddRange(snapshot
                .Where(t => t.IsCompletedSuccessfully && t.Result is not null)
                .SelectMany(t => t.Result!));
        }

        // Fallback: if the player didn't query the transcripts endpoint, but we did see
        // OTHER calls to the same drive item (labelPolicies, analytics, the cached transcode
        // endpoint, etc.), proactively query the transcripts-metadata endpoint ourselves
        // using the (drive-id, item-id) we harvested. This is the only reliable way to find
        // transcripts attached to a recording, since the player's behaviour is inconsistent
        // (some recordings trigger the fetch on player init, others only when CC is clicked).
        if (unique.Count == 0 && itemRefs.Length > 0)
        {
            foreach (var itemRef in itemRefs)
            {
                cancellationToken.ThrowIfCancellationRequested();
                var metadataUrl = $"{itemRef.Origin}{itemRef.ApiSegment}/drives/{itemRef.DriveId}/items/{itemRef.ItemId}" +
                    "?select=media%2Ftranscripts%2CaudioTracks&%24expand=media%2Ftranscripts%2Cmedia%2FaudioTracks";
                TranscriptEntry[]? entries;
                try
                {
                    var apiResponse = await context.APIRequest.GetAsync(metadataUrl, new APIRequestContextOptions
                    {
                        Timeout = 30_000
                    }).ConfigureAwait(false);
                    if (!apiResponse.Ok) continue;
                    var body = await apiResponse.BodyAsync().ConfigureAwait(false);
                    entries = ParseMetadataBytes(body, metadataUrl);
                }
                catch (Exception ex)
                {
                    warnings.Add(new ReplayWarning(
                        ReplayWarningCodes.CaptureStreamMetadataParseFailed,
                        $"Proactive transcripts-metadata fetch failed for {metadataUrl}: {ex.Message}",
                        Source: "stream",
                        Severity: ReplayWarningSeverities.Warning));
                    continue;
                }

                if (entries is not null && entries.Length > 0)
                {
                    unique.AddRange(entries);
                }
            }
        }

        // Dedupe across all sources (passive + proactive) by id.
        unique = unique
            .GroupBy(e => e.Id)
            .Select(g => g.First())
            .ToList();

        if (unique.Count == 0) return [];

        warnings.Add(new ReplayWarning(
            ReplayWarningCodes.CaptureStreamTranscriptDiscovered,
            $"SharePoint Stream metadata listed {unique.Count} transcript(s): " +
            string.Join(", ", unique.Select(e => $"{e.LanguageTag ?? "?"} ({e.Source ?? "unknown source"})")),
            Source: "stream",
            Severity: ReplayWarningSeverities.Info));

        var captionsDir = request.Run.GetPath("captions");
        Directory.CreateDirectory(captionsDir);
        var captions = new List<BrowserCapturedCaption>();
        var ordinalBase = 2000;
        var ordinal = 0;

        foreach (var entry in unique)
        {
            cancellationToken.ThrowIfCancellationRequested();
            ordinal++;

            byte[]? body;
            string? contentType;
            string downloadedFromUrl = entry.TemporaryDownloadUrl;

            // Try a sequence of URL variants in priority order, looking for the richest
            // response (Teams JSON with speaker info rather than the stripped VTT). Stop at
            // the first variant that returns a JSON-shaped body roughly matching the size
            // the metadata reported for the source file (257 KB JSON vs 108 KB VTT in the
            // observed case). Discovered by reverse-engineering the Stream player JS:
            //
            //   1) `?isformatjson=true&transcriptkey={id}` is the query the player's
            //      `fetchAndDecrypt` path uses for the CDN endpoint.
            //   2) `?$format=json` is the OData content-negotiation hint.
            //   3) `?format=json` is the non-OData fallback some endpoints honour.
            //   4) plain URL (returns stripped VTT) is the last-resort fallback.
            //
            // For each variant we send `Accept: application/json` to nudge any server-side
            // content negotiation in the same direction.
            var variants = new[]
            {
                AppendQueryParam(AppendQueryParam(entry.TemporaryDownloadUrl, "isformatjson", "true"), "transcriptkey", entry.Id),
                AppendQueryParam(entry.TemporaryDownloadUrl, "$format", "json"),
                AppendQueryParam(entry.TemporaryDownloadUrl, "format", "json"),
                entry.TemporaryDownloadUrl
            };

            body = null;
            contentType = null;
            foreach (var variant in variants)
            {
                cancellationToken.ThrowIfCancellationRequested();
                var (varBody, varContentType) = await TryDownloadAsync(context, variant, accept: "application/json", cancellationToken).ConfigureAwait(false);
                if (varBody is null || varBody.Length == 0) continue;
                body = varBody;
                contentType = varContentType;
                downloadedFromUrl = variant;
                // Stop early on the first variant that yielded JSON \u2014 that's the richer
                // format we're hunting. Subsequent variants would only overwrite to lower-fidelity
                // VTT shapes.
                if (LooksLikeJson(varBody)) break;
            }

            if (body is null)
            {
                warnings.Add(new ReplayWarning(
                    ReplayWarningCodes.CaptureStreamTranscriptParseFailed,
                    $"Stream transcript download failed for {entry.TemporaryDownloadUrl}.",
                    Source: "stream",
                    Severity: ReplayWarningSeverities.Warning));
                continue;
            }

            if (body.Length == 0)
            {
                warnings.Add(new ReplayWarning(
                    ReplayWarningCodes.CaptureStreamTranscriptParseFailed,
                    $"Stream transcript download returned an empty body for {entry.TemporaryDownloadUrl}.",
                    Source: "stream",
                    Severity: ReplayWarningSeverities.Warning));
                continue;
            }

            var rawText = System.Text.Encoding.UTF8.GetString(body);
            var languageSlug = string.IsNullOrWhiteSpace(entry.LanguageTag)
                ? "stream"
                : entry.LanguageTag.Replace('/', '-').Replace('\\', '-');

            // Persist the raw body for audit, even when we can convert to VTT.
            var rawExtension = InferRawExtension(contentType, entry.DisplayName, rawText);
            var rawFileName = $"stream-{ordinal:0000}-{languageSlug}{rawExtension}";
            var rawPath = Path.Combine(captionsDir, rawFileName);
            try
            {
                await File.WriteAllBytesAsync(rawPath, body, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                warnings.Add(new ReplayWarning(
                    ReplayWarningCodes.CaptureStreamTranscriptParseFailed,
                    $"Failed to persist Stream transcript body to {rawPath}: {ex.Message}",
                    Source: "stream",
                    Severity: ReplayWarningSeverities.Warning));
                continue;
            }

            // Convert to WebVTT for the downstream SubtitleConverter.
            var vtt = TryConvertToVtt(rawText);
            if (vtt is null)
            {
                warnings.Add(new ReplayWarning(
                    ReplayWarningCodes.CaptureStreamTranscriptParseFailed,
                    $"Stream transcript at {rawPath} did not match any recognised VTT or Teams-JSON shape. " +
                    $"Raw body kept; inspect manually.",
                    Source: "stream",
                    Severity: ReplayWarningSeverities.Warning));
                continue;
            }

            var vttFileName = $"stream-{ordinal:0000}-{languageSlug}.vtt";
            var vttPath = Path.Combine(captionsDir, vttFileName);
            await File.WriteAllTextAsync(vttPath, vtt, cancellationToken).ConfigureAwait(false);

            var hash = Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(vtt))).ToLowerInvariant();
            captions.Add(new BrowserCapturedCaption(
                Ordinal: ordinalBase + ordinal,
                Url: entry.TemporaryDownloadUrl,
                RelativePath: $"captions/{vttFileName}",
                InferredLanguage: entry.LanguageTag,
                LanguageSource: string.IsNullOrWhiteSpace(entry.LanguageTag) ? null : "stream-metadata-languageTag",
                ByteCount: vtt.Length,
                ContentSha256: hash,
                ContentType: "text/vtt"));

            warnings.Add(new ReplayWarning(
                ReplayWarningCodes.CaptureStreamTranscriptDownloaded,
                $"Downloaded SharePoint Stream transcript: language={entry.LanguageTag ?? "unknown"}, " +
                $"source={entry.Source ?? "unknown"}, autoGenerated={entry.IsAutoGenerated}, " +
                $"bytes={body.Length:N0} \u2192 {vttPath}.",
                Source: "stream",
                Severity: ReplayWarningSeverities.Info));
        }

        return captions;
    }

    /// <summary>
    /// Fetch a transcript URL once via the authenticated context with an optional Accept
    /// header. Returns (body, contentType) on success, (null, null) on error. Errors are
    /// swallowed silently because we may retry the same URL with different headers.
    /// </summary>
    private static async Task<(byte[]? Body, string? ContentType)> TryDownloadAsync(
        IBrowserContext context,
        string url,
        string? accept,
        CancellationToken cancellationToken)
    {
        try
        {
            var options = new APIRequestContextOptions { Timeout = 60_000 };
            if (!string.IsNullOrWhiteSpace(accept))
            {
                options.Headers = new Dictionary<string, string>
                {
                    ["Accept"] = accept
                };
            }
            var response = await context.APIRequest.GetAsync(url, options).ConfigureAwait(false);
            if (!response.Ok) return (null, null);

            var body = await response.BodyAsync().ConfigureAwait(false);
            string? ct = null;
            var headers = response.Headers;
            if (headers is not null && headers.TryGetValue("content-type", out var headerValue))
            {
                ct = headerValue;
            }
            return (body, ct);
        }
        catch
        {
            return (null, null);
        }
    }

    /// <summary>
    /// Append <c>name=value</c> to the URL's query string, preserving any existing
    /// parameters. URI-safe escaping for the value.
    /// </summary>
    private static string AppendQueryParam(string url, string name, string value)
    {
        var separator = url.Contains('?') ? '&' : '?';
        return $"{url}{separator}{Uri.EscapeDataString(name)}={Uri.EscapeDataString(value)}";
    }

    /// <summary>
    /// True when the first non-whitespace byte of the body is <c>{</c> or <c>[</c>, indicating
    /// a JSON document. Cheap pre-check before attempting full parse \u2014 lets us discard
    /// servers that ignored our <c>isformatjson=true</c> hint and served VTT anyway.
    /// </summary>
    private static bool LooksLikeJson(byte[] body)
    {
        for (var i = 0; i < body.Length; i++)
        {
            var b = body[i];
            if (b == (byte)' ' || b == (byte)'\t' || b == (byte)'\r' || b == (byte)'\n' || b == 0xEF || b == 0xBB || b == 0xBF) continue;
            return b == (byte)'{' || b == (byte)'[';
        }
        return false;
    }

    /// <summary>
    /// Best-effort conversion of a transcript response body to standard WebVTT. Handles two
    /// shapes seen in the wild: raw WebVTT (passes through unchanged) and Microsoft Teams
    /// transcript JSON (converted cue-by-cue). Returns null when the input matches neither
    /// shape \u2014 caller emits a parse-failed warning in that case.
    /// </summary>
    internal static string? TryConvertToVtt(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return null;

        // Case 1: already WebVTT \u2014 just normalise line endings.
        var trimmed = raw.TrimStart('\uFEFF', ' ', '\t', '\r', '\n');
        if (trimmed.StartsWith("WEBVTT", StringComparison.OrdinalIgnoreCase))
        {
            return trimmed.Replace("\r\n", "\n", StringComparison.Ordinal);
        }

        // Case 2: looks like JSON \u2014 try to parse known Teams shapes.
        if (trimmed.StartsWith('{') || trimmed.StartsWith('['))
        {
            return TryConvertTeamsJsonToVtt(trimmed);
        }

        return null;
    }

    private static string? TryConvertTeamsJsonToVtt(string json)
    {
        try
        {
            using var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;

            // Find the cue list. Known shapes in priority order:
            //   { entries: [ ... ] }            (Teams transcript schema:
            //                                    "$schema":"http://stream.office.com/schemas/transcript.json"
            //                                    \u2014 the rich format we get with ?isformatjson=true)
            //   { events: [ ... ] }             (legacy)
            //   { recognizedPhrases: [...] }    (Speech Service shape)
            //   [ ... ]                         (raw array at the root)
            JsonElement entries;
            if (root.ValueKind == JsonValueKind.Array)
            {
                entries = root;
            }
            else if (root.TryGetProperty("entries", out entries) && entries.ValueKind == JsonValueKind.Array)
            {
                // ok
            }
            else if (root.TryGetProperty("events", out entries) && entries.ValueKind == JsonValueKind.Array)
            {
                // ok
            }
            else if (root.TryGetProperty("recognizedPhrases", out entries) && entries.ValueKind == JsonValueKind.Array)
            {
                // ok
            }
            else
            {
                return null;
            }

            var cues = new List<(double startSeconds, double endSeconds, string speaker, string text)>();
            foreach (var entry in entries.EnumerateArray())
            {
                if (entry.ValueKind != JsonValueKind.Object) continue;

                var (start, end) = ExtractCueTiming(entry);
                if (start < 0 || end <= start) continue;

                var text = ExtractCueText(entry);
                if (string.IsNullOrWhiteSpace(text)) continue;

                var speaker = ExtractSpeaker(entry) ?? string.Empty;
                cues.Add((start, end, speaker, text.Trim()));
            }

            if (cues.Count == 0) return null;

            var sb = new System.Text.StringBuilder();
            sb.AppendLine("WEBVTT");
            sb.AppendLine();
            for (var i = 0; i < cues.Count; i++)
            {
                var c = cues[i];
                sb.Append((i + 1).ToString(System.Globalization.CultureInfo.InvariantCulture));
                sb.AppendLine();
                sb.Append(FormatVttTimestamp(c.startSeconds));
                sb.Append(" --> ");
                sb.Append(FormatVttTimestamp(c.endSeconds));
                sb.AppendLine();
                if (!string.IsNullOrWhiteSpace(c.speaker))
                {
                    // <v Speaker> tag form: SubtitleConverter.ParseSegments recognises this and
                    // attaches the speakerDisplayName to the resulting TranscriptSegment.
                    sb.Append("<v ").Append(c.speaker.Replace('>', ' ')).Append('>');
                }
                sb.AppendLine(c.text);
                sb.AppendLine();
            }
            return sb.ToString();
        }
        catch
        {
            return null;
        }
    }

    private static (double startSeconds, double endSeconds) ExtractCueTiming(JsonElement entry)
    {
        // Try numeric (seconds) start/end first.
        if (TryGetDouble(entry, "startTime", out var s1) && TryGetDouble(entry, "endTime", out var e1))
        {
            return (s1, e1);
        }
        if (TryGetDouble(entry, "start", out var s2) && TryGetDouble(entry, "end", out var e2))
        {
            return (s2, e2);
        }
        // Teams sometimes uses "startOffset" / "endOffset" as ISO 8601 duration strings.
        var startOffset = TryGetString(entry, "startOffset");
        var endOffset = TryGetString(entry, "endOffset");
        if (!string.IsNullOrWhiteSpace(startOffset) && !string.IsNullOrWhiteSpace(endOffset))
        {
            var parsedStart = TryParseDuration(startOffset!);
            var parsedEnd = TryParseDuration(endOffset!);
            if (parsedStart >= 0 && parsedEnd > parsedStart)
            {
                return (parsedStart, parsedEnd);
            }
        }
        return (-1, -1);
    }

    private static string? ExtractCueText(JsonElement entry)
    {
        // Direct text field
        var direct = TryGetString(entry, "text")
            ?? TryGetString(entry, "displayText")
            ?? TryGetString(entry, "spokenText")
            ?? TryGetString(entry, "caption");
        if (!string.IsNullOrWhiteSpace(direct)) return direct;

        // recognizedPhrases shape: { nBest: [{ display: "..." }] }
        if (entry.TryGetProperty("nBest", out var nBest) && nBest.ValueKind == JsonValueKind.Array)
        {
            foreach (var item in nBest.EnumerateArray())
            {
                var disp = TryGetString(item, "display");
                if (!string.IsNullOrWhiteSpace(disp)) return disp;
                var lex = TryGetString(item, "lexical");
                if (!string.IsNullOrWhiteSpace(lex)) return lex;
            }
        }
        return null;
    }

    private static string? ExtractSpeaker(JsonElement entry)
    {
        return TryGetString(entry, "speakerDisplayName")
            ?? TryGetString(entry, "speakerName")
            ?? TryGetString(entry, "speaker");
    }

    private static double TryParseDuration(string iso)
    {
        if (TimeSpan.TryParse(iso, System.Globalization.CultureInfo.InvariantCulture, out var ts))
        {
            return ts.TotalSeconds;
        }
        try
        {
            return System.Xml.XmlConvert.ToTimeSpan(iso).TotalSeconds;
        }
        catch
        {
            return -1;
        }
    }

    private static string FormatVttTimestamp(double seconds)
    {
        if (double.IsNaN(seconds) || seconds < 0) seconds = 0;
        var totalMs = (long)Math.Round(seconds * 1000.0);
        var hours = totalMs / 3_600_000;
        var minutes = (totalMs / 60_000) % 60;
        var secs = (totalMs / 1_000) % 60;
        var ms = totalMs % 1_000;
        return $"{hours:D2}:{minutes:D2}:{secs:D2}.{ms:D3}";
    }

    private static string InferRawExtension(string? contentType, string? displayName, string rawText)
    {
        var trimmed = rawText.TrimStart('\uFEFF', ' ', '\t', '\r', '\n');
        if (trimmed.StartsWith("WEBVTT", StringComparison.OrdinalIgnoreCase)) return ".vtt";
        if (trimmed.StartsWith('{') || trimmed.StartsWith('[')) return ".json";
        if (!string.IsNullOrWhiteSpace(contentType))
        {
            var ct = contentType.ToLowerInvariant();
            if (ct.Contains("json", StringComparison.Ordinal)) return ".json";
            if (ct.Contains("vtt", StringComparison.Ordinal)) return ".vtt";
            if (ct.Contains("srt", StringComparison.Ordinal)) return ".srt";
            if (ct.Contains("xml", StringComparison.Ordinal)) return ".xml";
        }
        if (!string.IsNullOrWhiteSpace(displayName))
        {
            var ext = Path.GetExtension(displayName);
            if (!string.IsNullOrWhiteSpace(ext) && ext.Length <= 6) return ext;
        }
        return ".bin";
    }

    private static string? TryGetString(JsonElement element, string property)
    {
        if (element.TryGetProperty(property, out var value) && value.ValueKind == JsonValueKind.String)
        {
            return value.GetString();
        }
        return null;
    }

    private static bool TryGetBool(JsonElement element, string property)
    {
        if (element.TryGetProperty(property, out var value))
        {
            if (value.ValueKind == JsonValueKind.True) return true;
            if (value.ValueKind == JsonValueKind.False) return false;
        }
        return false;
    }

    private static bool TryGetDouble(JsonElement element, string property, out double value)
    {
        value = 0;
        if (!element.TryGetProperty(property, out var v)) return false;
        switch (v.ValueKind)
        {
            case JsonValueKind.Number:
                return v.TryGetDouble(out value);
            case JsonValueKind.String:
                return double.TryParse(v.GetString(), System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out value);
            default:
                return false;
        }
    }

    internal sealed record TranscriptEntry(
        string Id,
        string? DisplayName,
        string? LanguageTag,
        string? TranscriptType,
        string? Source,
        bool IsAutoGenerated,
        bool IsDefault,
        string TemporaryDownloadUrl);

    /// <summary>
    /// A unique (drive-id, item-id) tuple observed during browser capture, used to
    /// proactively query the transcripts-metadata endpoint when the player itself doesn't.
    /// </summary>
    internal sealed record DriveItemRef(string Origin, string ApiSegment, string DriveId, string ItemId);
}
